//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Forma_zajęć
    {
        public int ID { get; set; }
        public Nullable<int> Wykład { get; set; }
        public Nullable<int> Ćwiczenia { get; set; }
        public Nullable<int> Laboratorium { get; set; }
        public Nullable<int> Projekt { get; set; }
        public Nullable<int> Seminarium { get; set; }
    }
}
