//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Karta_przedmiotu_Autor_karty_przedmiotu
    {
        public int Karta_przedmiotuID { get; set; }
        public int Autor_karty_przedmiotuID { get; set; }
    }
}
