//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Program_kształcenia
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Program_kształcenia()
        {
            this.Karta_przedmiotu = new HashSet<Karta_przedmiotu>();
        }
    
        public int ID { get; set; }
        public Nullable<int> PoziomKształcenia { get; set; }
        public Nullable<int> ProfilKształcenia { get; set; }
        public Nullable<int> FormaStudiów { get; set; }
        public string Język { get; set; }
        public string Specjalność { get; set; }
        public Nullable<int> KierunekID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Karta_przedmiotu> Karta_przedmiotu { get; set; }
        public virtual Kierunek Kierunek { get; set; }
    }
}
