//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Treść_programowa
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Treść_programowa()
        {
            this.Temat_zajęć = new HashSet<Temat_zajęć>();
            this.Temat_zajęć1 = new HashSet<Temat_zajęć>();
        }
    
        public int ID { get; set; }
        public Nullable<int> FormaZajeć { get; set; }
        public int Karta_przedmiotuID { get; set; }
        public Nullable<int> Karta_PrzedmiotuID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Temat_zajęć> Temat_zajęć { get; set; }
        public virtual Karta_przedmiotu Karta_przedmiotu { get; set; }
        public virtual Karta_przedmiotu Karta_przedmiotu1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Temat_zajęć> Temat_zajęć1 { get; set; }
    }
}
