//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Typ_oceny
    {
        public int ID { get; set; }
        public Nullable<int> Formująca { get; set; }
        public Nullable<int> Podsumowująca { get; set; }
    }
}
