//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Wymaganie_wstępne
    {
        public int ID { get; set; }
        public string Nazwa { get; set; }
        public Nullable<int> Karta_PrzedmiotuID { get; set; }
    
        public virtual Karta_przedmiotu Karta_przedmiotu { get; set; }
    }
}
