//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Zakres_PEK
    {
        public int ID { get; set; }
        public Nullable<int> Wiedza { get; set; }
        public Nullable<int> Umiejętność { get; set; }
        public Nullable<int> Kompetencji { get; set; }
    }
}
